services:
  postgres:
    image: postgres:14.13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
